<a href="https://colab.research.google.com/github/rohit8077/Machine-learning-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l1 = [10,20,30]
l2 = [40,50,60]
print(l1+l2)

[10, 20, 30, 40, 50, 60]


In [ ]:
a= np.array([10,20,30])
b =np.array ([40,50,60])
print(a)
print(b)
print (a+b)

[10 20 30]
[40 50 60]
[50 70 90]


In [ ]:
a= np.array([[10,20,30],[40,50,60],[70,80,90]])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#slicing

a= np.array([[10,20,30,40,50,60],[40,50,60,40,50,60]])
print(a[0:5,0:4])
print(np.shape(a))
print(np.size(a))
print(np.ndim(a))
print(a.dtype)

[[10 20 30 40]
 [40 50 60 40]]
(2, 6)
12
2
int64


In [ ]:
#Inspecting an Array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:3])
print(type(arr))

[6 7]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4])
print(arr[1:3])

[2 3]


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[11,12,13,14]])
print(arr[0:3,0:2])
print(arr[2,0:2])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

[[ 1  2]
 [ 5  6]
 [11 12]]
[11 12]
(3, 4)
12
2
int64


In [ ]:
a=([[10,20,30,40,50,60,],[ 40,50,60,40,50,60]])
arr = np.array(a)
print(a)
print(arr.shape) #rows, column
print(np.ndim(arr))
print(len(arr)) #number of nested values
print(arr.size)#number of element
print(type(arr)) #type of Variable
print(arr.dtype) #dataype of array
print(arr.astype(str)) #Conversion of Datatype

[[10, 20, 30, 40, 50, 60], [40, 50, 60, 40, 50, 60]]
(2, 6)
2
2
12
<class 'numpy.ndarray'>
int64
[['10' '20' '30' '40' '50' '60']
 ['40' '50' '60' '40' '50' '60']]


In [ ]:
# Mathemathical Operation and function On Array (add)
arr1 =np.array([10,20,30,40,50,60,])
arr2= np.array([ 40,50,60,40,50,60])
print(arr1+arr2)
print(np.add(arr1,arr2))

[ 50  70  90  80 100 120]
[ 50  70  90  80 100 120]


In [ ]:
#subtract
arr1 =np.array([90,20,30,40,50,60,])
arr2= np.array([ 40,50,60,40,50,60])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[ 50 -30 -30   0   0   0]
[ 50 -30 -30   0   0   0]


In [ ]:
# Multiple
arr1 =np.array([10,20,30,40,50,60,])
arr2= np.array([ 40,50,60,40,50,60])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[ 400 1000 1800 1600 2500 3600]
[ 400 1000 1800 1600 2500 3600]


In [ ]:
#divide
arr1 =np.array([10,20,30,40,50,60,])
arr2= np.array([ 40,50,60,40,50,60])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[0.25 0.4  0.5  1.   1.   1.  ]
[0.25 0.4  0.5  1.   1.   1.  ]


In [ ]:
#power
arr1=([10,20,30])
arr2=([2])
print(np.power(arr1, arr2))

[100 400 900]


In [ ]:
#combining and spliting Array

arr1 =np.array([[10,20],[30,40],[90,80]])
arr2= np.array([[40,50],[60,40],[50,60]])
print(np.concatenate([arr1,arr2]))


[[10 20]
 [30 40]
 [90 80]
 [40 50]
 [60 40]
 [50 60]]


In [ ]:
print(np.concatenate([arr1,arr2],axis =0))

[[10 20]
 [30 40]
 [90 80]
 [40 50]
 [60 40]
 [50 60]]


In [ ]:
print(np.hstack([arr1,arr2])) #Horizontal Concatenation

[[10 20 40 50]
 [30 40 60 40]
 [90 80 50 60]]


In [ ]:
print(np.vstack([arr1,arr2])) #Vertical Concatenation

[[10 20]
 [30 40]
 [90 80]
 [40 50]
 [60 40]
 [50 60]]


In [ ]:
a = np.array([20,30,40,50,60])
print(np.array_split(a,1))
print(b[1])

[array([20, 30, 40, 50, 60])]
50


In [ ]:
#adding and Removing
a= np.array([[10,20],[30,40]])
print(np.append(a,90))

[10 20 30 40 90]


In [ ]:
print(np.insert(a,1,[50], axis=1)) # array, index, Value

[[10 50 20]
 [30 50 40]]


In [ ]:
print(np.delete(a,0, axis =0))

[[30 40]]


In [ ]:
#sorting
arr1 = np.array([1,5,9,8,7,3,12,6])
arr = np.array([[1,5,9,8],[7,3,12,6]])
print(np.sort(arr))
print(np.sort(arr1))

[[ 1  5  8  9]
 [ 3  6  7 12]]
[ 1  3  5  6  7  8  9 12]


In [ ]:
#search
arr1 = np.array([10,20,30,40,50,60,])
s=np.where(arr1 % 2==0)
print(s)


(array([0, 1, 2, 3, 4, 5]),)


In [ ]:
arr1 = np.array([10,20,30,40,50,60,])
s=np.searchsorted(arr1 , 40)
print(s)


3


In [ ]:
#filters
ar = np.array([40,5,60,70])
#fa = [True, False,True, False]
fa = ar % 2 ==1
new = ar[fa]
print(new)

[5]


In [ ]:
# Aggregating Function in NumPy
a = np.array([10,20,30,40])
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.size(a))
print(np.mean(a))
print(np.median(a))
print(np.cumsum(a))
print(np.cumprod(a))

40
10
100
4
25.0
25.0
[ 10  30  60 100]
[    10    200   6000 240000]


In [ ]:
a = [10,50,90,80,70,30,102,60]
b = [1,5,9,8,7,3,12,6]
price = np.array(a)
quantity= np.array(b)

print(price ,"\n", quantity)
print(np.sum(price))
n= np.cumprod([price, quantity], axis = 0)
print(n[1].sum())

[ 10  50  90  80  70  30 102  60] 
 [ 1  5  9  8  7  3 12  6]
492
3874


In [ ]:
#statistical Functions
import statistics as stats # for using the mode then we are import the statistics
Baked_food = [100,300,200,500,600,120,140]
a = np.array(Baked_food)
print(np.mean(Baked_food)) # Sum of all the value/number of Values
print(np.median(a)) # central value sfter sorting
print(stats.mode(a))
print(np.std(Baked_food))
print(np.var(Baked_food))

280.0
200.0
100
183.3030277982336
33600.0


In [ ]:
#- 1 represent inversly proportional relationship
# 1 represent proportional relationship
#0 means no relationship
tabacco_consumption = [30,40,50,60,10,20]
Death = [110,233,456,234,265,523]

print(np.corrcoef([tabacco_consumption, Death]))

[[ 1.         -0.08033859]
 [-0.08033859  1.        ]]


In [ ]:
price1 = [ 300,100,350,150,200]
sale = [10,4,20,7,13]
print(np.corrcoef([price1, sale]))

[[1.         0.85216724]
 [0.85216724 1.        ]]
